package com.harukisolodev.harukistream.data

data class BrowseVideo(
    val id: String,
    val url: String,
    val title: String,
    val uploader: String,
    val thumbnailUrl: String,
    val durationSeconds: Long = 0L,
    val viewCount: Long = -1L,
    val uploadText: String = "",
    val shortForm: Boolean = false,
    val service: String = "YouTube",
    val playbackUrl: String = "",
    val sessionCookie: String = "",
    val uploaderAvatarUrl: String = "",
    val uploaderVerified: Boolean = false
)

enum class BrowseEntityType { CHANNEL, PLAYLIST }
enum class CollectionTab { VIDEOS, PLAYLISTS }

data class BrowseEntity(
    val id: String,
    val url: String,
    val name: String,
    val thumbnailUrl: String = "",
    val subtitle: String = "",
    val description: String = "",
    val verified: Boolean = false,
    val itemCount: Long = -1L,
    val type: BrowseEntityType
)

data class BrowseCollectionState(
    val entity: BrowseEntity? = null,
    val title: String = "",
    val subtitle: String = "",
    val description: String = "",
    val thumbnailUrl: String = "",
    val videos: List<BrowseVideo> = emptyList(),
    val playlists: List<BrowseEntity> = emptyList(),
    val selectedTab: CollectionTab = CollectionTab.VIDEOS,
    val loading: Boolean = false,
    val loadingMore: Boolean = false,
    val hasMore: Boolean = false,
    val error: String = ""
)

data class ShortCommentsState(
    val items: List<VideoComment> = emptyList(),
    val totalCount: Int = 0,
    val loading: Boolean = false,
    val hasMore: Boolean = false,
    val error: String = ""
)

data class SubtitleTrack(
    val id: String,
    val label: String,
    val languageCode: String,
    val url: String,
    val mimeType: String = "application/ttml+xml",
    val autoGenerated: Boolean = false
)

data class VideoComment(
    val id: String,
    val author: String,
    val authorAvatarUrl: String,
    val text: String,
    val likeCount: Int = -1,
    val uploadText: String = "",
    val verified: Boolean = false,
    val pinned: Boolean = false
)

data class WatchDetails(
    val description: String = "",
    val uploaderAvatarUrl: String = "",
    val uploaderUrl: String = "",
    val uploaderVerified: Boolean = false,
    val subscriberCount: Long = -1L,
    val viewCount: Long = -1L,
    val likeCount: Long = -1L,
    val uploadText: String = "",
    val subtitles: List<SubtitleTrack> = emptyList()
)

data class WatchState(
    val item: BrowseVideo? = null,
    val media: AnalyzedMedia? = null,
    val related: List<BrowseVideo> = emptyList(),
    val relatedLoadingMore: Boolean = false,
    val relatedHasMore: Boolean = true,
    val relatedError: String = "",
    val details: WatchDetails = WatchDetails(),
    val comments: List<VideoComment> = emptyList(),
    val commentsCount: Int = 0,
    val commentsLoading: Boolean = false,
    val commentsHasMore: Boolean = false,
    val commentsError: String = "",
    val collectionName: String = "",
    val collectionPosition: Int = -1,
    val collectionSize: Int = 0,
    val collectionPrevious: BrowseVideo? = null,
    val collectionNext: BrowseVideo? = null,
    val collectionItems: List<BrowseVideo> = emptyList(),
    val loading: Boolean = false,
    val error: String = ""
)

data class BrowseState(
    val youtubeHome: List<BrowseVideo> = emptyList(),
    val youtubeSearch: List<BrowseVideo> = emptyList(),
    val youtubeSearchChannels: List<BrowseEntity> = emptyList(),
    val youtubeSearchPlaylists: List<BrowseEntity> = emptyList(),
    val youtubeSearchSuggestion: String = "",
    val youtubeSuggestions: List<String> = emptyList(),
    val youtubeVideoSuggestions: List<BrowseVideo> = emptyList(),
    val youtubeShorts: List<BrowseVideo> = emptyList(),
    val youtubeLoading: Boolean = false,
    val youtubeLoadingMore: Boolean = false,
    val youtubeHasMore: Boolean = true,
    val youtubeShortsLoading: Boolean = false,
    val youtubeShortsLoadingMore: Boolean = false,
    val youtubeShortsHasMore: Boolean = true,
    val youtubeError: String = "",
    val youtubeShortsError: String = "",
    val youtubeQuery: String = "",
    val youtubeSearchDraft: String = "",
    val youtubeHomeNavigationToken: Long = 0L,
    val youtubeCategory: String = "For You",
    val verticalMedia: Map<String, AnalyzedMedia> = emptyMap(),
    val verticalLoading: Set<String> = emptySet(),
    val verticalErrors: Map<String, String> = emptyMap(),
    val shortComments: Map<String, ShortCommentsState> = emptyMap(),
    val collection: BrowseCollectionState = BrowseCollectionState(),
    val novaAi: NovaAiState = NovaAiState(),
    val watch: WatchState = WatchState()
)
